package com.user.model.entities.enums;

public enum SecurityLogEnum {
    PASSWORD_CHANGE,
    PASSWORD_FORGET,
    PASSWORD_RESET,
    EMAIL_ADDED,
    EMAIL_REMOVED,
    EMAIL_CHANGE_PRIORITY,
    EMAIL_CHANGE_PREFERENCE,
    EMAIL_ADDED_BACKUP,
    EMAIL_REMOVED_BACKUP,
    EMAIL_RESEND_CONFIRMATION,
    EMAIL_CONFIRMED,
    ADDRESS_ADDED,
    ADDRESS_REMOVED,
}
